// Automatically generated by CMAKE

#include "version_samples2cams.hpp"

namespace samples2cams
{
    const unsigned AtracsysGitVersion::Major( 7 );
    const unsigned AtracsysGitVersion::Minor( 5 );
    const unsigned AtracsysGitVersion::Revision( 0 );
    const unsigned AtracsysGitVersion::Build( 0 );
    const unsigned AtracsysGitVersion::TimeStamp( 1743687677 );
    const std::string AtracsysGitVersion::SoftwareVersion( "v7.5.0" );
    const std::string AtracsysGitVersion::SoftwareVersionFull( "v7.5.0 (1743687677) Linux-5.15.0-1074-azure" );
    const std::string AtracsysGitVersion::Sha1( "c63817ca2543f864ed4b67f11e3534256c4d5dc7" );
}
