// Automatically generated by CMAKE

#include "version_advancedApi.hpp"

namespace advancedApi
{
    const unsigned AtracsysGitVersion::Major( 1 );
    const unsigned AtracsysGitVersion::Minor( 3 );
    const unsigned AtracsysGitVersion::Revision( 0 );
    const unsigned AtracsysGitVersion::Build( 0 );
    const unsigned AtracsysGitVersion::TimeStamp( 1714643549 );
    const std::string AtracsysGitVersion::SoftwareVersion( "v1.3.0" );
    const std::string AtracsysGitVersion::SoftwareVersionFull( "v1.3.0 (1714643549) Windows-6.3.9600" );
    const std::string AtracsysGitVersion::Sha1( "6fae151b71cc6e19875dfcfa226ec25d83ce270c" );
}
