#pragma once
// Automatically generated by CMAKE

#include <string>

namespace advancedApi
{
    class AtracsysGitVersion
    {
    public:
        static const unsigned Major;
        static const unsigned Minor;
        static const unsigned Revision;
        static const unsigned Build;
        static const unsigned TimeStamp;
        static const std::string SoftwareVersion;
        static const std::string SoftwareVersionFull;
        static const std::string Sha1;
    };
}
