// Automatically generated by CMAKE

#include "version_samples2cams.hpp"

namespace samples2cams
{
    const unsigned AtracsysGitVersion::Major( 7 );
    const unsigned AtracsysGitVersion::Minor( 4 );
    const unsigned AtracsysGitVersion::Revision( 0 );
    const unsigned AtracsysGitVersion::Build( 0 );
    const unsigned AtracsysGitVersion::TimeStamp( 1714643549 );
    const std::string AtracsysGitVersion::SoftwareVersion( "v7.4.0" );
    const std::string AtracsysGitVersion::SoftwareVersionFull( "v7.4.0 (1714643549) Windows-6.3.9600" );
    const std::string AtracsysGitVersion::Sha1( "ca6fec0f175269a129647b5207d39f89e7768229" );
}
