// Automatically generated by CMAKE

#include "version_advancedApi.hpp"

namespace advancedApi
{
    const unsigned AtracsysGitVersion::Major( 1 );
    const unsigned AtracsysGitVersion::Minor( 4 );
    const unsigned AtracsysGitVersion::Revision( 0 );
    const unsigned AtracsysGitVersion::Build( 0 );
    const unsigned AtracsysGitVersion::TimeStamp( 1743687677 );
    const std::string AtracsysGitVersion::SoftwareVersion( "v1.4.0" );
    const std::string AtracsysGitVersion::SoftwareVersionFull( "v1.4.0 (1743687677) Linux-5.15.0-1074-azure" );
    const std::string AtracsysGitVersion::Sha1( "2459e8a9b32bb56f25e95a04ec1a403c4344f666" );
}
